### ISSUE TITLE
ClassLoaderLeakPreventorFactory not found

### ISSUE THREAD

**Issue by ophillan** [mjiderhamn/classloader-leak-prevention#73]
Added the listener, but getting a NoClassDefFoundError for java.lang.NoClassDefFoundError: se/jiderhamn/classloader/leak/prevention/ClassLoaderLeakPreventorFactory at startup.
When checking source code, it's not imported anywhere in the ClassLoaderLeakPreventorListener.java. Just used out of the blue. Is it supposed to be an inner class or something that was removed in some version and forgotten about? 

Anyhow, the project is currently unusable in this state.

**Comment by mjiderhamn** [comment]
No import is needed since `ClassLoaderLeakPreventorFactory` is in the same package as `ClassLoaderLeakPreventorListener`. However it is in a different `jar`. If you are using Maven, the `classloader-leak-prevention-core` artifact should be a transitive dependency of `classloader-leak-prevention-servlet`/`classloader-leak-prevention-servlet3`.

I need to know more about your setup in order to help.

**Comment by ophillan** [comment]
I used Ivy, and no jars other than the servlet one were created after building with either servlet or servlet3 reference.

**Comment by mjiderhamn** [comment]
I'm surprised to hear that, although I've never used Ivy. You should be able to resolve this by explicitly adding `classloader-leak-prevention-core` to your config.

**Comment by mjiderhamn** [comment]
You haven't explicitly set `transitive="false"`, have you?

**Comment by mjiderhamn** [comment]
Closing due to lack of feedback
